# Generated by Django 4.1.7 on 2023-04-01 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('can_create_task', 'Can create task'),)},
        ),
    ]
