# Generated by Django 4.2 on 2023-05-05 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, max_length=150, verbose_name='language'),
        ),
    ]
