# Generated by Django 4.1.7 on 2023-04-01 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.task'),
        ),
    ]
