# Generated by Django 4.1.7 on 2023-04-02 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_submission_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='input1',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='input2',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='output1',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='output2',
            field=models.TextField(null=True),
        ),
    ]
