# Generated by Django 4.1.7 on 2023-04-02 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_task_input1_task_input2_task_output1_task_output2'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='prepod',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='student',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('AC', 'Успешно'), ('WA', 'Неправильный вывод'), ('E', 'Ошибка')], max_length=3),
        ),
    ]
