# Generated by Django 4.1.7 on 2023-04-09 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_submission_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='slug',
        ),
        migrations.AddField(
            model_name='task',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
