# Generated by Django 4.2 on 2023-05-05 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_task_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='language',
            field=models.CharField(blank=True, max_length=150, verbose_name='language'),
        ),
    ]
